### ISSUE TITLE
Which dataset to train PCA for holidays dataset?

### ISSUE THREAD

**Issue by pfllo** [fmaglia/keras_rmac_plus#1]
Hi, fmaglia,
Thanks for sharing the great project. 
I'm interested in reproducing the results in the Holidays dataset, but I can't find any guidance in the code.
Specifically, I would like to know which dataset is used to train the PCA for retrieving the Holidays dataset?

Thanks.

**Comment by fmaglia** [comment]
Hi pfllo,

I used oxford5k to train PCA for the Holidays dataset.
However, if you want to use the Holidays dataset, firstly you need to download it from the website (http://lear.inrialpes.fr/~jegou/data.php), secondly unzip and subdivide in two folders (Db and query) and then manually rotate the images if you want also to test the pipeline on the Holidays rotated version.
Before to start, remember to resize the images to 1024x768, respecting the aspect ratio.

**Comment by Metatr0n** [comment]
Hi, Federico,

Thank you for interesting paper and project!
I want to use proposed approach for others datasets. My answer is: are there any rules or approaches for choosing dataset for training PCA? Does the domain affect the choice?
 
Thanks in advance
