### ISSUE TITLE
Using with other datasets (domains)

### ISSUE THREAD

**Issue by Metatr0n** [fmaglia/keras_rmac_plus#3]
Hi, Federico,

Thank you for interesting paper and project!
I want to use proposed approach for others datasets. My answer is: are there any rules or approaches for choosing dataset for training PCA? Does the domain affect the choice?

Thanks in advance

**Comment by fmaglia** [comment]
Hey,
sorry for the late response.
I think that the only important rule for choosing dataset for training PCA is that you need to use dataset similar to your problem topic. So, if you want to retrieve car images, the PCA dataset needs to contain images of cars, autos.
